- hosts: master
  tasks:
   - name: update kubeadm kubelet kubectl on k8 control node
     package:
       name:
         - kubeadm
         - kubelet
         - kubectl
       state: latest
       
   - name: upgrade cluster
     shell: "kubeadm upgrade apply v1.23.3 -y" #add required version
     
   - name: restart kubelet service
     systemd:
       name: kubelet
       state: restarted
       daemon_reload: yes
       

- hosts: all
  tasks:
   - name: update kubeadm
     package:
       name: kubeadm
       state: latest

   - name: update kubelet
     package:
       name: kubelet
       state: latest

       
- hosts: workers
  tasks:
   - name: worker node kubeadm upgrade 
     shell: kubeadm upgrade node
     
   - name: restart kubelet service
     systemd:
       name: kubelet
       state: restarted
       daemon_reload: yes
       
