- hosts: all
  tasks:
   - name: stop k8 running services
     systemd:
       name:
         - docker
         - kubelet
       state: stopped

   - name: update Docker
     yum:
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
       state: latest

   - name: update kubelet
     yum:
       name: kubelet
       state: latest

   - name: update kubeadm
     yum:
       name: kubeadm
       state: latest

- hosts: master
  tasks:
   - name: update kubectl
     yum:
       name: kubectl
       state: latest

- hosts: all
  tasks:
   - name: reboot k8 cluster nodes
     reboot: